### PR TITLE
[WIP] Removes deprecation from upcoming Ember 2.12 release.

### PR DESCRIPTION
**Pull request by workmanw**
Let's hold on merging this until after Ember-Data's change lands in their beta channel. See: https://github.com/emberjs/data/pull/4743 .

### CODE REVIEW

**Comment by workmanw** [comment]
@jakesjews The upstream commit was cherry-picked into the beta channel. :). Okay to merge this one? After that, I'll rerun the tests with the other PR and then rebase it and we should be passing for the beta :).

**Comment by jakesjews** [comment]
@workmanw sorry about the late response. Looks good 👍

**Comment by workmanw** [comment]
@jakesjews No worries :) If you have a moment can you take a look at #232.

**Comment by jakesjews** [comment]
@workmanw will do

**Pull request merged**
