### PR TITLE
update to ember-cli 2.9.1

### PR DESCRIPTION
**Pull request by jakesjews**

### CODE REVIEW

**Comment by jakesjews** [comment]
@workmanw I think we might be due for a release after this PR

**Comment by workmanw** [comment]
@jakesjews Sorry I've been late on responding. I'm going to review this first thing tomorrow morning. I'm very much 👍 on switching ember-try to use LTS releases for backwards compat. I think that's a smart move. Eyeballing, everything looks in order here. I'll clone and confirm tomorrow.

**Comment by jakesjews** [comment]
For some reason CI is failing on canary even though it's set to allow failures so I gotta look into that too.

**Comment by jakesjews** [comment]
I ended up removing the canary ember-try scenario for now. It looks like its hitting some sort of infinite loop which is causing CI to fail.

**Comment by workmanw** [comment]
Really sorry about the delay this week. Thanks for keeping up with this. I'm very much :+1: on checking the LTS versions, I think that's a great idea.

**Comment by jakesjews** [comment]
no problem there isn't really a rush on this

**Pull request merged**
