### PR TITLE
update to ember 2.6

### PR DESCRIPTION
**Pull request by jakesjews**

### CODE REVIEW

**Comment by workmanw** [comment]
👍

**Comment by slindberg** [comment]
Thanks guys, doesn't look like there's any backwards incompatible changes, so it should be released as 2.3.2, yeah?

**Comment by jakesjews** [comment]
Yeah it should be good to go. Thanks!

**Comment by workmanw** [comment]
Agreed. We haven't seen any incompatibilities and we've been using ember-data 2.6 since it was released.

**Pull request merged**
