### PR TITLE
Update to use Ember Data 3.0

### PR DESCRIPTION
**Pull request by rondale-sc**

### CODE REVIEW

**Comment by jakesjews** [comment]
@rondale-sc looks awesome thanks for doing this! @workmanw does this look good to you?

**Comment by workmanw** [comment]
👍 No concerns here.

**Comment by rondale-sc** [comment]
@workmanw Do you have a trajectory for the next release to be cut from NPM.  I'd much prefer not to pin to a commit to get on 3.0 beta.  :beers:

**Comment by workmanw** [comment]
Yea, let's make sure #285 is closable, then we'll cut a new release.

**Comment by rwjblue** [comment]
Sorry for the delay, ya looks good to me.

**Comment by workmanw** [comment]
@rondale-sc @jakesjews So we generally like to keep all of our ember packages all in lock step. However none of the 3 packages (ember, data, cli) have a v3 out yet. I think it would be a mistake for us to cut 3.0 right now while still using 2.18 packages. That said, we could release a 3.0.0-beta.1. I would be okay with that. Thoguths?

**Comment by jakesjews** [comment]
I'm in agreement. I think a beta seems like a good idea.

**Comment by rondale-sc** [comment]
@workmanw Totally.  I think pushing a beta now would be in perfect line with everything.  The Ember.js 3.0 beta moves to stable on Monday so this'll be perfect timing! :beers:

**Comment by workmanw** [comment]
@rondale-sc 3.0.0-beta.1 was published to npm about an hour ago.

**Pull request merged**
