### PR TITLE
Update to Ember 3.0

### PR DESCRIPTION
**Pull request by jakesjews**
Also ran the Qunit codemod to convert tests to the modern ember testing API

### CODE REVIEW

**Comment by jakesjews** [comment]
@workmanw does this look cool to you?

**Comment by workmanw** [comment]
Yeap. Thanks a lot for taking this on. Looks like it was a bit of a grueling refactor.

**Comment by workmanw** [comment]
Once we merge this, we can get a new release out.

**Comment by jakesjews** [comment]
@workmanw the codemod actually did the bulk of the work. It was pretty amazing

**Pull request merged**
