### PR TITLE
Fix bug where setting array fragment attr to null can cause error

### PR DESCRIPTION
**Pull request by Techn1x**
Fixes https://github.com/lytics/ember-data-model-fragments/issues/306

EDIT: I'll add a test soon

### CODE REVIEW

**Comment by jakesjews** [comment]
@Techn1x looks like some small lint errors for trailing spaces then I think this looks good

**Comment by Techn1x** [comment]
No problem. The test I added is also slightly broken, will fix that up too (unfortunately for some reason `ember test` is broken on my dev machine for this addon..)

**Comment by jakesjews** [comment]
@workmanw this looks good to me how about you?

**Comment by workmanw** [comment]
@Techn1x :+1: for the great test and fix. I think Ember's copy is deprecated right? And we just started using `ember-copy` instead. Can you rebase on to master and check that. If so, I think ti's as easy as swapping the import.

**Comment by Techn1x** [comment]
Thanks guys. Have done the rebase and now using ember-copy

**Pull request merged**
