### PR TITLE
richgt - Upgrade to work with Ember Data 3.16 (latest LTS)

### PR DESCRIPTION
**Pull request by richgt**

### CODE REVIEW

**Comment by jelhan** [comment]
@richgt Thanks for creating a merge request. Makes it easier to follow.

Just for me to understand, how is this different from #339 and how does it address the issue described in https://github.com/lytics/ember-data-model-fragments/pull/339#issuecomment-537731217? Or did something changed upstream in Ember Data and this isn't a problem anymore?

**Comment by richgt** [comment]
@jelhan - this is a larger refactor to use Ember Data's recordData functionality. I've been working on this refactor with @igorT and @runspired from the Ember Data team. I'm not sure it completely addresses the issue you have in #339 yet, but we're still working on it.

**Comment by pjcarly** [comment]
I want you all to know i am following this PR closely, thanks a lot for the work.

If I can do anything to test or help out with the port to RecordData (even though my ED/RecordData knowledge is limited) let me know or ping me on Discord.

**Comment by basz** [comment]
> I want you all to know i am following this PR closely, thanks a lot for the work.

I second that! muchos ❤️

**Comment by richgt** [comment]
> I want you all to know i am following this PR closely, thanks a lot for the work.
> 
> If I can do anything to test or help out with the port to RecordData (even though my ED/RecordData knowledge is limited) let me know or ping me on Discord.

Thanks. We're down to one failing test, then some cleanup. Hopefully sometime next week for a release.

**Comment by knownasilya** [comment]
@richgt what's the status here?

**Comment by richgt** [comment]
@knownasilya - I've commented out the last test, and started testing in my repository. Things look pretty good. I have 2 TODOs to resolve, and @igorT has a few as well. I'm working on mine today, @igorT expects to be able to get to his on Friday. We hope to have a release candidate available sometime early next week. We will need to find somebody who has merge privileges to this repo to merge this, so anybody reading who does, please let me know.

**Comment by GavinJoyce** [comment]
> We hope to have a release candidate available sometime early next week. We will need to find somebody who has merge privileges to this repo to merge this, so anybody reading who does, please let me know.

@workmanw 👋 it looks like you might have merge privileges. Perhaps you might be able to assist here?

**Comment by jakesjews** [comment]
I have merge privileges and am keeping a close eye on these changes.

**Comment by erkie** [comment]
Do you guys have Paypal.me links or similar so I can buy you a couple of beers/coffee/toilet paper?

**Comment by richgt** [comment]
> Do you guys have Paypal.me links or similar so I can buy you a couple of beers/coffee/toilet paper?

@erkie - thanks, but my company's paying me for this one since we're so dependent on it also. Can't speak for Igor. If you feel obliged, a charity I'm close with: https://fundraise.rallyfoundation.org/campaign/childhood-cancer-doesnt-take-a-coffee-break/c278838

**Comment by patocallaghan** [comment]
@igorT and @richgt thanks for this amazing work 🙌

Just an FYI in case any else uses it but Ember Data Factory Guy (which supports Model Fragments) doesn't appear to be compatible out-of-the-box with this refactor. I've opened a [tracking issue](https://github.com/danielspaniel/ember-data-factory-guy/issues/417) to look into it more.

**Comment by basz** [comment]
Thanks all for pulling this thing forward... Works perfectly so far...

**Comment by richgt** [comment]
Updated the title here. This will be a breaking change, and will only work with EmberData 3.16+ (and possibly stop working again in the future, as expected), so we'll have to release a major version, I believe.

**Comment by patocallaghan** [comment]
@richgt considering you mention above `(and possibly stop working again in the future, as expected)`, is this because the library is using non-standard private APIs still?

Would it be possible to document how Model Fragments is now using the Record Data API and also what the potential future problems are? i.e. the ED private APIs being used and why they are needed etc. This will be useful to future maintainers of Model Fragments.

**Comment by richgt** [comment]
> @richgt considering you mention above `(and possibly stop working again in the future, as expected)`, is this because the library is using non-standard private APIs still?
> 
> Would it be possible to document how Model Fragments is now using the Record Data API and also what the potential future problems are? i.e. the ED private APIs being used and why they are needed etc. This will be useful to future maintainers of Model Fragments.

Seems like a pretty reasonable ask. Let me try to work through this with @igorT as we work through our remaining TODOs before release.

**Comment by richgt** [comment]
Just to clarify, I may do this as a follow-up, since it doesn't appear this has ever been done for this repo, other than in the "Compatibility" section of the readme with a statement: 

> This project makes extensive use of private Ember Data APIs and is therefore sensitive to minor changes in new Ember Data releases, regardless of semver guarantees. Every effort is made to maintain compatibility with the latest version, but updates always take time.

**Comment by basz** [comment]
FYI there are several 'debugger' statements in source right now that I'm pretty sure are not supposed to be there... :-)

**Comment by erkie** [comment]
Not sure if you've got this covered, but we're testing out this brand and getting a bunch of 

```

**Comment by richgt** [comment]
> Not sure if you've got this covered, but we're testing out this branch and getting a bunch of
> 
> ```
> DEPRECATION: Use of `merge` has been deprecated. Please use `assign` instead. [deprecation id: ember-polyfills.deprecate-merge] See https://emberjs.com/deprecations/v3.x/#toc_ember-polyfills-deprecate-merge for more details.
>         at logDeprecationStackTrace (http://dev.feeder.co:3001/ember-cli-path/assets/vendor.js:50862:21)
>         at HANDLERS.<computed> (http://dev.feeder.co:3001/ember-cli-path/assets/vendor.js:50959:9)
>         at raiseOnDeprecation (http://dev.feeder.co:3001/ember-cli-path/assets/vendor.js:50889:9)
>         at HANDLERS.<computed> (http://dev.feeder.co:3001/ember-cli-path/assets/vendor.js:50959:9)
>         at invoke (http://dev.feeder.co:3001/ember-cli-path/assets/vendor.js:50971:9)
>         at deprecate (http://dev.feeder.co:3001/ember-cli-path/assets/vendor.js:50927:28)
>         at Object.merge (http://dev.feeder.co:3001/ember-cli-path/assets/vendor.js:55338:47)
>         at FragmentRecordData.pushData (http://dev.feeder.co:3001/ember-cli-path/assets/vendor.js:124180:15)
>         at InternalModel.setupData (http://dev.feeder.co:3001/ember-cli-path/assets/vendor.js:111329:42)
> ```
> 
> In development.
> 
> With
> 
> ```
> "ember-data-model-fragments": "git+https://github.com/richgt/ember-data.model-fragments.git#b4a9be1bae3291e6b6b94ac38010a9ce2fb57474",
> ```
> 
> So not current HEAD.
> 
> However, we're running this in production as well (YOLO) and it's working great!

Hadn't seen that yet, but will take a look now. Looks like we only have 2 uses of merge, so should be easy enough to resolve. Thanks!

**Comment by richgt** [comment]
@erkie - FYI, `merge` issue should be resolved.

**Comment by patocallaghan** [comment]
@richgt @igorT I've managed to reproduce an issue which I found when trying this branch out in a test build in our app and was also happening in our tests. I was able to reproduce it in a repo using factory guy but I'll try and get a reproduction in the app without requiring factory guy over the weekend.

Details are here: https://github.com/danielspaniel/ember-data-factory-guy/issues/417#issuecomment-632907508

**Comment by richgt** [comment]
@jakesjews - I believe this is ready to be merged at this point. I'm going to look into the issue that @patocallaghan is running into, but I've got a green build with my app, and several others have gotten good success with their apps as well. Please let me know what else we need to do to publish a release here.

**Comment by patocallaghan** [comment]
I've managed to replicate the issue we're having without using Factory Guy so the problem is not specifically tied to that library.

Model Fragments doesn't provide an API to create Fragment Arrays (see issue https://github.com/lytics/ember-data-model-fragments/issues/272) so a workaround we use in our app in cases where we want to set a fragmentArray (and possibly what Factory Guy also does) is to create a fragment using `store.createFragment` with a fragment array on it. We'll then take that fragment array property value and pass it to a `store.createRecord` call elsewhere. This is an extremely simplified case below.

```js
let parentClone = store.createFragment('parent', {
  children: [{
    name: 'Pat'
  }]
});
let grandparent = store.createRecord('grandparent', {
  parent: {
    children: parentClone.children,
  }
});
```

I've added a failing test to https://github.com/patocallaghan/model-fragments-bug (which is no longer private 🙈) and also to the branch using the older model fragments/ember-data (it passes there). I'm not sure if this idiomatic usage of Model Fragments but it's something we've done successfully in the past.

@richgt @jakesjews Don't block the release on my account but happy to work with you folks to get a patch out afterwards.

**Comment by richgt** [comment]
@patocallaghan - If `createFragmentArray` existed, what would the code look like instead? I don't see a reason not to potentially implement `createFragmentArray` as an additional API, though I'd like to get @igorT's thoughts on that.

**Comment by basz** [comment]
I'm currently seeing the following;

Nested properties (could be ember-changeset) OR properties of fragments (could be e-d-m-f) will not update correctly into the form control (could be ember-bootstrap).

Since ember changeset was also refactored recently too the problem might come from there. I've created a minimal application that shows the issue.

show https://ember.bushbaby.nl/
source https://github.com/basz/ember-form
also https://discordapp.com/channels/480462759797063690/483601670685720591/714407522450276354

**Comment by erkie** [comment]
I just found a crash in the latest commit. Not sure if it is just not intended to work? But setting the an array fragment with a new array causes an exception on save.

```js
// app/models/thing.js
import DS from "ember-data";
import { array } from "ember-data-model-fragments/attributes";

export default DS.Model.extend({
  tags: array("string")
});

// tests/unit/models/thing-test.js

import { module, test } from 'qunit';
import { setupTest } from 'ember-qunit';
import { run } from '@ember/runloop';

module('Unit | Model | thing', function(hooks) {
  setupTest(hooks);

  test('should this work?', function() {
    const thing = run(() =>
      this.owner.lookup('service:store').createRecord('thing')
    );

    thing.set("tags", ["hello", "world"]);
    run(() => thing.save());
  });
});
```

Crashes with:

```
            TypeError: Cannot read property '_recordData' of undefined
                at http://localhost:7357/assets/vendor.js:92803:35
                at Array.forEach (<anonymous>)
                at FragmentRecordData.willCommit (http://localhost:7357/assets/vendor.js:92802:30)
                at InternalModel.adapterWillCommit (http://localhost:7357/assets/vendor.js:84724:24)
                at Store.scheduleSave (http://localhost:7357/assets/vendor.js:88751:21)
                at InternalModel.save (http://localhost:7357/assets/vendor.js:84226:20)
                at Class.save (http://localhost:7357/assets/vendor.js:72478:38)
                at http://localhost:7357/assets/tests.js:17:29
                at Backburner._run (http://localhost:7357/assets/vendor.js:57557:25)
                at Backburner.run (http://localhost:7357/assets/vendor.js:57298:19)
```

**Comment by patocallaghan** [comment]
@richgt So I'd expect something like the following to work

```js
this.store.createFragmentArray('child', [{ name: 'Pat' }]);
```

But saying that, it got me thinking as to why we were even using this pattern in the first place (this code was written a while ago). I made some changes to our code to work in raw json rather than passing around objects and it now works. I'm currently going whack-a-mole through our tests to fix up them to use json directly. For example instead of doing:

```js
let parentClone = store.createFragment('parent', {
  children: [{
    name: 'Pat'
  }]
});
grandparent.parent.set('children', parentClone.children);
```

```js
let parentClone = store.createFragment('parent', {
  children: [{
    name: 'Pat'
  }]
});
grandparent.parent.set('children', [{
    name: 'Pat'
}]);
```

and the fragmentArrays seem to be hydrated correctly. Also for Factory Guy users it means you always need to use `build` when constructing fragments to put into other fragments or models rather than `make`.

**Comment by richgt** [comment]
@erkie / @basz - going to spend some time today trying to look into these issues. I'll let you know what I find.

**Comment by basz** [comment]
@richgt, please know that probably my issues were not related to EDMF but to ember-changeset. Been working on those and two down one to go...

**Comment by richgt** [comment]
> @richgt, please know that probably my issues were not related to EDMF but to ember-changeset. Been working on those and two down one to go...

Sounds good. Going to look at @erkie's issue, as it seems pretty directly related to EDMF.

**Comment by richgt** [comment]
Rebased to all one commit, @erkie - your issue should be resolved.

**Comment by patocallaghan** [comment]
@richgt @igorT I put together a detailed description and a potential patch for the [issue I mentioned above](https://github.com/lytics/ember-data-model-fragments/pull/360/#issuecomment-633257505)

**Comment by jakesjews** [comment]
@richgt @igorT would you prefer me to merge this PR as is now or do you want to look at @patocallaghan's PR first?

**Comment by richgt** [comment]
> @richgt @igorT would you prefer me to merge this PR as is now or do you want to look at @patocallaghan's PR first?

@jakesjews - @igorT and I are syncing at 1:30 PST today. We'll have an update shortly after that.

**Comment by richgt** [comment]
@jakesjews - we're good to merge this as-is, and we'll get @patocallaghan's PR in separately. Have to look into a few things there. Do you have NPM creds to get this pushed up as a new version to NPM also?

**Comment by jakesjews** [comment]
@richgt I think I have NPM creds but its been awhile so hopefully I'm right.

**Comment by jakesjews** [comment]
Looks like I do have permission. I released the changes as 5.0.0-beta.0

**Pull request merged**
