### PR TITLE
ES6-ify this addon.

### PR DESCRIPTION
**Pull request by workmanw**
* [x] Function shorthand
* [x] Interpolated strings and single-quote.
  - Skipped the tests package because there were a LOT of double quote strings and I didn't want to make this review worse. 
* [x] const/let instead of var
* [x] spread arguments when calling `this._super()`
* [x] Fat arrow.
* [ ] ~ESLint~ _(Another PR later)_

I know this is a big PR to review. No rush, do it when you have time. I separated various topics into separate commits incase there was something we wanted to backout. My plan is to squash them all down into a single ES6 commit. Let me know what you think, happy to change anything add or remove stuff.

My motivation was to:
1. Get the code style more consistent (we had been writing ES6 stuff as new PRs were merged, but we still had a lot of ES5 stuff from the old'n days). 
2. Install ESLint and get a sane configuration (more on that to come in a future PR).

### CODE REVIEW

**Comment by jakesjews** [comment]
nice!

**Comment by workmanw** [comment]
Build passing now :) Also added Ember 2.11 (the oldest we support on master) to the try config.

**Comment by jakesjews** [comment]
@workmanw gave this a look over and our app's test suite passes with this so it gets a 👍 from me

**Comment by workmanw** [comment]
Awesome!! Thanks for the quick review. I know this one was probably tedious. I'll get it squashed and merged. Then onto an eslint PR.

**Pull request merged**
