### PR TITLE
fragments invoke ready callback when they are created

### PR DESCRIPTION
**Pull request by danielspaniel**
Howdy, this relates the the issue #250

### CODE REVIEW

**Comment by workmanw** [comment]
I'm 👍 . @jakesjews

**Comment by jakesjews** [comment]
@workmanw looks good to me too

**Comment by workmanw** [comment]
Thanks @danielspaniel ! I'm looking to cut a new release soon. Unfortunately there is an upstream ember-data bug I'm trying to get resolved first. Shouldn't be too much longer.

**Comment by danielspaniel** [comment]
ok  thanks for heads up @workmanw  .. was just about to ask when new release was arriving!

**Pull request merged**
