### PR TITLE
WIP: support Ember Data 3.13

### LINKED ISSUE #338: Incompatibility with ember-data 3.13.0
This error appears as soon as you upgrade from e-d 3.12.x to e-d 3.13.0

```There was an error running your app in fastboot. More info about the error: 
 TypeError: Cannot read property 'id' of null
    at new InternalModel (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/@ember-data/store/-private.js:4697:1)
    at Store.createFragment (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-data-model-fragments/ext.js:134:1)
    at createFragment (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-data-model-fragments/fragment.js:213:1)
    at setupFragment (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-data-model-fragments/attributes.js:97:1)
    at EditionModel.get (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-data-model-fragments/attributes.js:259:1)
    at /var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:3324:1
    at untrack (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:1247:1)
    at ComputedProperty.get (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:3323:1)
    at EditionModel.CPGETTER_FUNCTION [as saturday] (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:1044:1)
    at EditionService.get starts [as starts] (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/pawchewgo/services/edition.js:45:1)
    at getPossibleMandatoryProxyValue (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:1269:1)
    at get (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:1342:1)
    at /var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:565:1
    at track (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:1224:1)
    at NestedPropertyReference.compute (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:564:1)
    at NestedPropertyReference.value (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:376:1)
    at valueOf (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:4617:1)
    at Array.map (<anonymous>)
    at CapturedPositionalArguments.value (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:4594:1)
    at ClassBasedHelperReference.compute (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:738:1)
    at ClassBasedHelperReference.value (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:376:1)
    at ContentTypeReference.value (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:498:1)
    at ReferenceCache.initialize (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/reference.js:357:1)
    at ReferenceCache.peek (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/reference.js:326:1)
    at Function.initialize (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:847:1)
    at Object.evaluate (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:824:1)
    at AppendOpcodes.evaluate (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:73:1)
    at LowLevelVM.evaluateSyscall (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:3295:1)
    at LowLevelVM.evaluateInner (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:3241:1)
    at LowLevelVM.evaluateOuter (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:3233:1)
    at VM.next (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:5299:1)
    at TemplateIteratorImpl.next (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:5335:1)
    at RootState.render (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5614:1)
    at TransactionRunner.runInTransaction (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:2109:1)
    at runInTransaction (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:2238:1)
    at InertRenderer._renderRoots (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5911:1)
    at InertRenderer._renderRootsTransaction (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5949:1)
    at InertRenderer._renderRoot (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5868:1)
    at InertRenderer._appendDefinition (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5783:1)
    at InertRenderer.appendOutletView (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5769:1)
    at invokeWithOnError (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:349:1)
    at Queue.flush (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:229:1)
    at DeferredActionQueues.flush (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:426:1)
    at Backburner._end (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:960:1)
    at Backburner._boundAutorunEnd (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-28643HSC1Hg6tjrh6/out-388-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:629:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)```

### PR DESCRIPTION
**Pull request by jelhan**
Closes #338

### CODE REVIEW

**Comment by jelhan** [comment]
I've tried to debug the broken serialization. I think the issue is, that our record is not created through [`InternalModelFactory`'s](https://github.com/emberjs/data/blob/v3.13.1/packages/store/addon/-private/system/store/internal-model-factory.ts) build method. It seems like Ember Data is creating another instance of `InternalModel` for the same record, which is used on serialization. I don't see any option to use `InternalModelFactory` cause that one is private and not exported. It seems like even `InternalModel` is only exported for `ember-data-model-fragment`: https://github.com/emberjs/data/blob/e773f8bbf668a3436433060294a667ba94877bb8/packages/store/addon/-private/index.ts#L28-L30

I fear either help from Ember Data team or a bigger refactoring is needed.

**Comment by jelhan** [comment]
> It seems like Ember Data is creating another instance of `InternalModel` for the same record, which is used on serialization.

Let me elaborate on this one a little bit as it's critical for the situation. I think it's best to understand by a show case:

- Put a debugger here: https://github.com/lytics/ember-data-model-fragments/blob/master/addon/ext.js#L279
- Execute the serialization test.
- Inspect the decorator function for `createSnapshot` when it's executed for a fragment. I've used `name` fragment.

```js
// verify that you inspect the correct record
snapshot.modelName // "name"

// compare the identifier of the internal model via person record in store and via internal model of the snapshot
// you will see that both are the same
snapshot._store.peekRecord('person', '1').name._internalModel.identifier === snapshot._internalModel.identifier // true

// compare the internal model retrieved via person record in store and via internal model of the snapshot
// they should be the same but are not
snapshot._store.peekRecord('person', '1').name._internalModel === snapshot._internalModel // false
``

**Comment by jakesjews** [comment]
@jelhan thanks for looking into it! I was afraid this day would come eventually. I think the solution here is to rewrite everything to use the modelData api.

**Comment by GCheung55** [comment]
@jakesjews could this be a temp solution before the rewrite?

**Comment by jakesjews** [comment]
@GCheung55 I don't think this PR is working yet but if there was a way to get it going then it could work.

**Comment by jelhan** [comment]
@GCheung55 This PR is not working and if I didn't missed something there isn't a quick path to make it working. Ember Data changed there internal state management and do not export the required pieces that would be needed to adopt this change. As this addon was relying heavily on a private API that's not their fault. As far as I can see there isn't any other solution than rewriting this one based on newly exported public APIs.

@jakesjews Will close this one to avoid confusion.

**Pull request closed without merging**
