### PR TITLE
update to ember-cli 2.11

### PR DESCRIPTION
**Pull request by jakesjews**

### CODE REVIEW

**Comment by workmanw** [comment]
Oh man, I was just getting ready to do this, you beat me by just a few minutes.

**Comment by workmanw** [comment]
:+1: :100:

**Comment by jakesjews** [comment]
Thats funny. Figured I needed to do something after you did the heavy lifting on 2.11 compatiblity

**Comment by workmanw** [comment]
Oh hey @jakesjews, I just realized ember-data doesn't have a canary channel (git branch). It seems we just used master before (See: https://github.com/lytics/ember-data-model-fragments/commit/66d23d0507b28134fd0ca2ec200b11192c17e682). If you get a second, can you fix that? Probably don't need a PR, just commit it into master.

**Comment by jakesjews** [comment]
whoops. no problem 👍

**Comment by jakesjews** [comment]
@workmanw just pushed to master. Looks like CI is failing properly for canary now.

**Comment by workmanw** [comment]
Awesome. I have a fix for canary. It's pretty simple, just need to figure out a backwards compat strategy. Stay tuned :)

**Pull request merged**
